"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-29 18:27:15.133681
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB

# Entspricht app.db.base.JSONType: JSONB unter PostgreSQL, JSON sonst.
JSONType = sa.JSON().with_variant(JSONB, "postgresql")

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('host_player_id', sa.Uuid(), nullable=True),
    sa.Column('current_turn_number', sa.Integer(), nullable=False),
    sa.Column('event_seq', sa.BigInteger(), nullable=False),
    sa.Column('events_since_summary', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_code'), 'games', ['code'], unique=True)
    op.create_index(op.f('ix_games_status'), 'games', ['status'], unique=False)
    op.create_table('abilities',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost_stat', sa.String(length=40), nullable=True),
    sa.Column('cost_value', sa.Integer(), nullable=False),
    sa.Column('requirements', JSONType, nullable=False),
    sa.Column('effects', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name', name='uq_abilities_game_name')
    )
    op.create_index(op.f('ix_abilities_game_id'), 'abilities', ['game_id'], unique=False)
    op.create_table('facts',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at_seq', sa.BigInteger(), nullable=False),
    sa.Column('invalidated_at_seq', sa.BigInteger(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('data', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_created_at_seq'), 'facts', ['created_at_seq'], unique=False)
    op.create_index(op.f('ix_facts_game_id'), 'facts', ['game_id'], unique=False)
    op.create_index(op.f('ix_facts_invalidated_at_seq'), 'facts', ['invalidated_at_seq'], unique=False)
    op.create_index(op.f('ix_facts_key'), 'facts', ['key'], unique=False)
    op.create_table('game_settings',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('world', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('rule_complexity', sa.String(length=20), nullable=False),
    sa.Column('play_style', sa.String(length=20), nullable=False),
    sa.Column('tone', sa.String(length=30), nullable=False),
    sa.Column('campaign_type', sa.String(length=20), nullable=False),
    sa.Column('ruleset', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('ai_provider', sa.String(length=30), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('tts_enabled', sa.Boolean(), nullable=False),
    sa.Column('tts_provider', sa.String(length=30), nullable=True),
    sa.Column('audio_targets', JSONType, nullable=False),
    sa.Column('summary_every_n_events', sa.Integer(), nullable=False),
    sa.Column('debug_mode', sa.Boolean(), nullable=False),
    sa.Column('extra', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_settings_game_id'), 'game_settings', ['game_id'], unique=True)
    op.create_table('images',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_game_id'), 'images', ['game_id'], unique=False)
    op.create_table('inventories',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', name='uq_inventory_owner')
    )
    op.create_index(op.f('ix_inventories_game_id'), 'inventories', ['game_id'], unique=False)
    op.create_index(op.f('ix_inventories_owner_id'), 'inventories', ['owner_id'], unique=False)
    op.create_table('items',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('properties', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name', name='uq_items_game_name')
    )
    op.create_index(op.f('ix_items_game_id'), 'items', ['game_id'], unique=False)
    op.create_table('locations',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_discovered', sa.Boolean(), nullable=False),
    sa.Column('coordinates', JSONType, nullable=False),
    sa.Column('tags', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_game_id'), 'locations', ['game_id'], unique=False)
    op.create_table('players',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name', name='uq_players_game_name')
    )
    op.create_index(op.f('ix_players_game_id'), 'players', ['game_id'], unique=False)
    op.create_table('relationships',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'source_type', 'source_id', 'target_type', 'target_id', 'kind', name='uq_relationship_pair')
    )
    op.create_index(op.f('ix_relationships_game_id'), 'relationships', ['game_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_id'), 'relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_id'), 'relationships', ['target_id'], unique=False)
    op.create_table('scene_summaries',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('from_seq', sa.BigInteger(), nullable=False),
    sa.Column('to_seq', sa.BigInteger(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('highlights', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_summaries_game_id'), 'scene_summaries', ['game_id'], unique=False)
    op.create_table('characters',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('race', sa.String(length=60), nullable=False),
    sa.Column('class', sa.String(length=60), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('avatar', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('conditions', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index(op.f('ix_characters_game_id'), 'characters', ['game_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.Column('slot', sa.String(length=40), nullable=True),
    sa.Column('state', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_inventory_id'), 'inventory_items', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_id'), 'inventory_items', ['item_id'], unique=False)
    op.create_table('knowledge',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('fact_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('certainty', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('created_at_seq', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_created_at_seq'), 'knowledge', ['created_at_seq'], unique=False)
    op.create_index(op.f('ix_knowledge_game_id'), 'knowledge', ['game_id'], unique=False)
    op.create_index(op.f('ix_knowledge_subject_id'), 'knowledge', ['subject_id'], unique=False)
    op.create_index(op.f('ix_knowledge_subject_type'), 'knowledge', ['subject_type'], unique=False)
    op.create_table('turns',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scene_title', sa.String(length=200), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suggestions', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'number', name='uq_turns_game_number')
    )
    op.create_index(op.f('ix_turns_game_id'), 'turns', ['game_id'], unique=False)
    op.create_index(op.f('ix_turns_status'), 'turns', ['status'], unique=False)
    op.create_table('world_entities',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('is_known_to_party', sa.Boolean(), nullable=False),
    sa.Column('data', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_entities_game_id'), 'world_entities', ['game_id'], unique=False)
    op.create_index(op.f('ix_world_entities_kind'), 'world_entities', ['kind'], unique=False)
    op.create_table('actions',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('target_ref', sa.String(length=120), nullable=True),
    sa.Column('payload', JSONType, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('outcome', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_game_id'), 'actions', ['game_id'], unique=False)
    op.create_index(op.f('ix_actions_player_id'), 'actions', ['player_id'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_index(op.f('ix_actions_turn_id'), 'actions', ['turn_id'], unique=False)
    op.create_table('character_abilities',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('ability_id', sa.Uuid(), nullable=False),
    sa.Column('uses_left', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'ability_id', name='uq_character_ability')
    )
    op.create_index(op.f('ix_character_abilities_ability_id'), 'character_abilities', ['ability_id'], unique=False)
    op.create_index(op.f('ix_character_abilities_character_id'), 'character_abilities', ['character_id'], unique=False)
    op.create_table('character_stats',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'key', name='uq_character_stat_key')
    )
    op.create_index(op.f('ix_character_stats_character_id'), 'character_stats', ['character_id'], unique=False)
    op.create_table('entity_states',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('numeric_value', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['world_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'key', name='uq_entity_state_key')
    )
    op.create_index(op.f('ix_entity_states_entity_id'), 'entity_states', ['entity_id'], unique=False)
    op.create_table('events',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('audience_player_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', JSONType, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'seq', name='uq_events_game_seq')
    )
    op.create_index(op.f('ix_events_game_id'), 'events', ['game_id'], unique=False)
    op.create_index(op.f('ix_events_seq'), 'events', ['seq'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('narrations',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('audience_player_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('scene_title', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audience_player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrations_game_id'), 'narrations', ['game_id'], unique=False)
    op.create_table('quests',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('giver_entity_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('reward', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['giver_entity_id'], ['world_entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'title', name='uq_quests_game_title')
    )
    op.create_index(op.f('ix_quests_game_id'), 'quests', ['game_id'], unique=False)
    op.create_table('audio_jobs',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('narration_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('voice', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', JSONType, nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['narration_id'], ['narrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_jobs_game_id'), 'audio_jobs', ['game_id'], unique=False)
    op.create_index(op.f('ix_audio_jobs_narration_id'), 'audio_jobs', ['narration_id'], unique=False)
    op.create_index(op.f('ix_audio_jobs_status'), 'audio_jobs', ['status'], unique=False)
    op.create_table('dice_rolls',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=True),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('notation', sa.String(length=40), nullable=False),
    sa.Column('rolls', JSONType, nullable=False),
    sa.Column('modifier', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('degree', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dice_rolls_game_id'), 'dice_rolls', ['game_id'], unique=False)
    op.create_table('quest_states',
    sa.Column('quest_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', JSONType, nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_states_quest_id'), 'quest_states', ['quest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_states_quest_id'), table_name='quest_states')
    op.drop_table('quest_states')
    op.drop_index(op.f('ix_dice_rolls_game_id'), table_name='dice_rolls')
    op.drop_table('dice_rolls')
    op.drop_index(op.f('ix_audio_jobs_status'), table_name='audio_jobs')
    op.drop_index(op.f('ix_audio_jobs_narration_id'), table_name='audio_jobs')
    op.drop_index(op.f('ix_audio_jobs_game_id'), table_name='audio_jobs')
    op.drop_table('audio_jobs')
    op.drop_index(op.f('ix_quests_game_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_narrations_game_id'), table_name='narrations')
    op.drop_table('narrations')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_seq'), table_name='events')
    op.drop_index(op.f('ix_events_game_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_entity_states_entity_id'), table_name='entity_states')
    op.drop_table('entity_states')
    op.drop_index(op.f('ix_character_stats_character_id'), table_name='character_stats')
    op.drop_table('character_stats')
    op.drop_index(op.f('ix_character_abilities_character_id'), table_name='character_abilities')
    op.drop_index(op.f('ix_character_abilities_ability_id'), table_name='character_abilities')
    op.drop_table('character_abilities')
    op.drop_index(op.f('ix_actions_turn_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_player_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_game_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_world_entities_kind'), table_name='world_entities')
    op.drop_index(op.f('ix_world_entities_game_id'), table_name='world_entities')
    op.drop_table('world_entities')
    op.drop_index(op.f('ix_turns_status'), table_name='turns')
    op.drop_index(op.f('ix_turns_game_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_knowledge_subject_type'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_subject_id'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_game_id'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_created_at_seq'), table_name='knowledge')
    op.drop_table('knowledge')
    op.drop_index(op.f('ix_inventory_items_item_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_inventory_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_characters_game_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_scene_summaries_game_id'), table_name='scene_summaries')
    op.drop_table('scene_summaries')
    op.drop_index(op.f('ix_relationships_target_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_game_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_players_game_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_locations_game_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_items_game_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_inventories_owner_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_game_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_images_game_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_game_settings_game_id'), table_name='game_settings')
    op.drop_table('game_settings')
    op.drop_index(op.f('ix_facts_key'), table_name='facts')
    op.drop_index(op.f('ix_facts_invalidated_at_seq'), table_name='facts')
    op.drop_index(op.f('ix_facts_game_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_created_at_seq'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_abilities_game_id'), table_name='abilities')
    op.drop_table('abilities')
    op.drop_index(op.f('ix_games_status'), table_name='games')
    op.drop_index(op.f('ix_games_code'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
